/* generated by Svelte v3.38.3 */
import {
	SvelteComponent,
	append,
	assign,
	attr,
	check_outros,
	children,
	claim_component,
	claim_element,
	claim_space,
	create_component,
	destroy_component,
	detach,
	element,
	get_spread_object,
	get_spread_update,
	group_outros,
	init,
	insert,
	mount_component,
	safe_not_equal,
	space,
	transition_in,
	transition_out
} from '../web_modules/svelte/internal/index.mjs';

import Head from './head.js';
import Footeroo from './footeroo.js';
import { makeTitle } from '../scripts/make_title.js';

function create_fragment(ctx) {
	let html;
	let head;
	let t0;
	let body;
	let switch_instance;
	let t1;
	let footer;
	let footeroo;
	let t2;
	let script;
	let script_src_value;
	let current;

	head = new Head({
			props: {
				title: makeTitle(/*content*/ ctx[0].filename)
			}
		});

	const switch_instance_spread_levels = [
		/*content*/ ctx[0].fields,
		{ content: /*content*/ ctx[0] },
		{ allContent: /*allContent*/ ctx[2] },
		{ allLayouts: /*allLayouts*/ ctx[3] }
	];

	var switch_value = /*layout*/ ctx[1];

	function switch_props(ctx) {
		let switch_instance_props = {};

		for (let i = 0; i < switch_instance_spread_levels.length; i += 1) {
			switch_instance_props = assign(switch_instance_props, switch_instance_spread_levels[i]);
		}

		return { props: switch_instance_props };
	}

	if (switch_value) {
		switch_instance = new switch_value(switch_props(ctx));
	}

	footeroo = new Footeroo({});

	return {
		c() {
			html = element("html");
			create_component(head.$$.fragment);
			t0 = space();
			body = element("body");
			if (switch_instance) create_component(switch_instance.$$.fragment);
			t1 = space();
			footer = element("footer");
			create_component(footeroo.$$.fragment);
			t2 = space();
			script = element("script");
			this.h();
		},
		l(nodes) {
			html = claim_element(nodes, "HTML", { lang: true });
			var html_nodes = children(html);
			claim_component(head.$$.fragment, html_nodes);
			t0 = claim_space(html_nodes);
			body = claim_element(html_nodes, "BODY", { class: true });
			var body_nodes = children(body);
			if (switch_instance) claim_component(switch_instance.$$.fragment, body_nodes);
			t1 = claim_space(body_nodes);
			footer = claim_element(body_nodes, "FOOTER", { class: true });
			var footer_nodes = children(footer);
			claim_component(footeroo.$$.fragment, footer_nodes);
			footer_nodes.forEach(detach);
			t2 = claim_space(body_nodes);
			script = claim_element(body_nodes, "SCRIPT", { src: true, crossorigin: true });
			var script_nodes = children(script);
			script_nodes.forEach(detach);
			body_nodes.forEach(detach);
			html_nodes.forEach(detach);
			this.h();
		},
		h() {
			attr(footer, "class", "isFlexCentered");
			if (script.src !== (script_src_value = "https://kit.fontawesome.com/80f1b342a4.js")) attr(script, "src", script_src_value);
			attr(script, "crossorigin", "anonymous");
			attr(body, "class", "isGrid svelte-cy5z2m");
			attr(html, "lang", "en");
		},
		m(target, anchor) {
			insert(target, html, anchor);
			mount_component(head, html, null);
			append(html, t0);
			append(html, body);

			if (switch_instance) {
				mount_component(switch_instance, body, null);
			}

			append(body, t1);
			append(body, footer);
			mount_component(footeroo, footer, null);
			append(body, t2);
			append(body, script);
			current = true;
		},
		p(ctx, [dirty]) {
			const head_changes = {};
			if (dirty & /*content*/ 1) head_changes.title = makeTitle(/*content*/ ctx[0].filename);
			head.$set(head_changes);

			const switch_instance_changes = (dirty & /*content, allContent, allLayouts*/ 13)
			? get_spread_update(switch_instance_spread_levels, [
					dirty & /*content*/ 1 && get_spread_object(/*content*/ ctx[0].fields),
					dirty & /*content*/ 1 && { content: /*content*/ ctx[0] },
					dirty & /*allContent*/ 4 && { allContent: /*allContent*/ ctx[2] },
					dirty & /*allLayouts*/ 8 && { allLayouts: /*allLayouts*/ ctx[3] }
				])
			: {};

			if (switch_value !== (switch_value = /*layout*/ ctx[1])) {
				if (switch_instance) {
					group_outros();
					const old_component = switch_instance;

					transition_out(old_component.$$.fragment, 1, 0, () => {
						destroy_component(old_component, 1);
					});

					check_outros();
				}

				if (switch_value) {
					switch_instance = new switch_value(switch_props(ctx));
					create_component(switch_instance.$$.fragment);
					transition_in(switch_instance.$$.fragment, 1);
					mount_component(switch_instance, body, t1);
				} else {
					switch_instance = null;
				}
			} else if (switch_value) {
				switch_instance.$set(switch_instance_changes);
			}
		},
		i(local) {
			if (current) return;
			transition_in(head.$$.fragment, local);
			if (switch_instance) transition_in(switch_instance.$$.fragment, local);
			transition_in(footeroo.$$.fragment, local);
			current = true;
		},
		o(local) {
			transition_out(head.$$.fragment, local);
			if (switch_instance) transition_out(switch_instance.$$.fragment, local);
			transition_out(footeroo.$$.fragment, local);
			current = false;
		},
		d(detaching) {
			if (detaching) detach(html);
			destroy_component(head);
			if (switch_instance) destroy_component(switch_instance);
			destroy_component(footeroo);
		}
	};
}

function instance($$self, $$props, $$invalidate) {
	let { content } = $$props,
		{ layout } = $$props,
		{ allContent } = $$props,
		{ allLayouts } = $$props,
		{ env } = $$props;

	$$self.$$set = $$props => {
		if ("content" in $$props) $$invalidate(0, content = $$props.content);
		if ("layout" in $$props) $$invalidate(1, layout = $$props.layout);
		if ("allContent" in $$props) $$invalidate(2, allContent = $$props.allContent);
		if ("allLayouts" in $$props) $$invalidate(3, allLayouts = $$props.allLayouts);
		if ("env" in $$props) $$invalidate(4, env = $$props.env);
	};

	return [content, layout, allContent, allLayouts, env];
}

class Component extends SvelteComponent {
	constructor(options) {
		super();

		init(this, options, instance, create_fragment, safe_not_equal, {
			content: 0,
			layout: 1,
			allContent: 2,
			allLayouts: 3,
			env: 4
		});
	}
}

export default Component;